Locales['en'] = {
    ['noplayer'] = '~r~Netoliese nėra jokio asmens!',
    ['installing'] = 'Uždedama apykoja...',
    ['removed'] = '~g~Jūs pašalinote apykoją.',
    ['removing'] = 'Nuimama apykoja...',
    ['notfound'] = '~r~Apykoja neuždėta!',
    ['not_allowed'] = '~r~Jums neleidžiama naudoti šio daikto!',
    ['already'] = '~r~ Šiam asmeniui jau uždėta apykoja!',
    ['gps_required'] = '~r~Jūs neturite apykojos!',
    ['cutter_required'] = '~r~Jūs neturite žnyplių!',
    ['installed'] = '~g~Apykoja uždėta.',
    ['cancel'] = 'Norėdami atšaukti, paspauskite [E]',
    ['cancelled'] = '~r~Užduotis atšaukta!',
    ['alert'] = '~y~[Monitor Alert]~s~ : ~b~%s~s~ bando sulaužyti apykoją!',
    ['alertblip'] = '[Įspėjimas] : %s',
    ['failed'] = '~r~Jums nepavyko sulaužyti apykojos!',
    ['time_should'] = "Trukmė turėtų būti nuo %s iki %s minučių",
    ['number_error'] = "Turėtų būti skaičius!",
    ['set_time'] = "Nustatykite laiką (minutėmis)!",

}
