--------------------------------------
--<!>-- ASTUDIOS | DEVELOPMENT --<!>--
--------------------------------------
-- Language settings
Language = {
    Duty = {
        ['clock_in'] = 'Įsiregistruoti',
    },
    Progressbar = {
        ['getting_money'] = 'Pinigų gavimas ...',
        ['duty_status'] = 'Keičiama pareigų būsena...',
        ['standing_guard'] = 'Atsistojama į sargybą...',
        ['delivering_money'] = 'Pristatome pinigus...',
    },
    Success = {
        ['guard_task_complete'] = 'Apsaugos užduotis baigta',
        ['bank_task_complete'] = 'Pinigų perkėlimo užduotis atlikta',
    },
    Info = {
        ['place_the_money_in_truck'] = 'Įdėkite pinigus į sunkvežimį',
        ['transportation_task_delivery'] = 'Pristatykite pinigus Sąjungos indėlininkui',
        ['starting_guard_task'] = 'Nueikite į parodytą vietą ir budėkite toje vietoje '..Config.Tasks.GuardTask.GuardTime..' minutes',
        ['starting_transportation_task'] = 'Atvykite į nurodytą vietą ir pasiimkite paketą',
    },
    Error = {
        ['already_delivering'] = 'Jau atliekate pristatymą, užbaikite jį ir pradėkite naują',
        ['no_item'] = 'Jūs neturite pristatymo krepšio',
        ['stockade_not_close_enough'] = 'Banko sunkvežimis nėra pakankamai arti banko',
        ['not_onduty'] = 'Tu šiuo metu nedirbi',
        ['not_enough_money'] = 'Jūs neturite pakankamai pinigų nusipirkti paslaptingą dėžutę',
    },
    Menu = {
        ['wardrobe'] = 'Drabužinė',
        ['wardrobeicon'] = 'fas fa marškinėliai',
        ['duty'] = 'Laikas įėjimui / išėjimui',
        ['dutyicon'] = 'far fa dokumentai',
        ['dutytext'] = 'Nepamirškite įsiregistruoti ir išeiti!',
        ['exit'] = 'Grįžti',
        ['exiticon'] = 'fas fa-apskritimas-rodyklė-kairėn',
        ['garage'] = 'Garažas',
        ['garageicon'] = 'fas fa automobilis',
        ['jobclothing'] = 'Apsirenkite darbo aprangą',
        ['jobclothingicon'] = 'fas fa patikrinimas',
        ['outfits'] = 'Apranga',
        ['outfitsicon'] = 'fas fa debesis',
        ['park'] = 'Parkuoti transporto priemonę',
        ['parkicon'] = 'fas fa-parkavimas',
        ['personallocker'] = 'Asmeninė spintelė',
        ['personallockericon'] = 'fas fa atidaryta dėžė',
        ['guardtask'] = 'Stovintis apsaugos darbuotojas',
        ['guardtaskicon'] = 'fas fa-vartotojo skydas',
        ['transporttask'] = 'Pinigų gabenimas',
        ['transporttaskicon'] = 'fas fa-sunkvežimis',
        ['tasks'] = 'Užduotys',
        ['tasksicon'] = 'fas fa-užduotys',
    },
    Targeting = {
        ['bossmenu'] = 'Direktoriaus meniu',
        ['bossmenuicon'] = 'fas fa paprasta diagrama',
        ['wardrobe'] = 'Drabužinė',
        ['wardrobeicon'] = 'fas fa marškinėliai',
        ['garage'] = 'Garažas',
        ['garageicon'] = 'fas fa automobilis',
        ['storage'] = 'Saugykla',
        ['toggleduty'] = 'Perjungti pareigas',
        ['toggledutyicon'] = 'fas fa-dokumentai',
        ['tasks'] = 'Užduotys',
        ['tasksicon'] = 'fas fa užduotys',
    },
    Actions = {
        ['start_guardtask'] = 'Norėdami pradėti užduotį, paspauskite [E]',
        ['start_pickuptask'] = 'Paspauskite [E], kad pradėtumėte paėmimo užduotį',
        ['start_deliverytask']  = 'Norėdami pradėti pristatymo užduotį, paspauskite [E]',
    },
}
