Strings = {
    player_in_vehicle = 'Įtariamasis transporto priemonėje',
    player_in_vehicle_desc = 'Prieš tai darydamas išlaipink asmenį iš tr. priemonės',
    suspect_died_escort = 'Įtariamasis mirė',
    suspect_died_escort_desc = 'Įtariamasis numirė kol jūs jį lydėjote, todėl jį pametėte.',


    stop_escorting_interact = '[E] - Nustok lydėt',
    cant_wield = 'Negali užsidėti',
    cant_wield_desc = 'Šiuo metu negalite tuom naudotis!',



    jailed_player = 'Įtariamąjį įkalinote',
    jailed_player_desc = 'Įkalinote %s %s mėnesiams.',

    gps_active = 'GPS aktyvuotas',
    gps_active_desc = 'Žaidėjas %s aktyvavo savo GPS',
    gps_deactive = 'GPS Deactivated',
    gps_deactive_desc = 'Žaidėjas %s išjungė savo GPS',

    no_wsb = '^0[^3WARNING^0] wasabi_bridge was NOT started AFTER framework and/or BEFORE resource: %s',
    currency = '$',
    success = 'Pavyko',
    go_back = '< Grįžti atgal',
    cloakroom = 'Persirengimo kambarys',
    civilian_wear = 'Civilinė apranga',
    armoury_quantity_dialog = 'Kiekis užsakymui',
    quantity = 'Kiekis',
    invalid_amount = 'Netinkama suma',
    invalid_amount_desc = 'Įveskite tinkamą sumą',
    successful_purchase_desc = 'Sėkmingai užsisakei savo ginklus iš arsenalo',
    lacking_funds = 'Trūksta lėšų',
    lacking_funds_desc = 'Jūs neturite pakankamai lėšų banke šiam pirkiniui įsigyti',
    no_permission = 'Neturi leidimo to daryti',
    no_access_desc = 'Neturi teisės daryti šio veiksmo',
    key_map_cuff = 'Surakinti asmenį',
    key_map_tackle = 'Pargriauti asmenį kol bėgi',
    key_map_job = 'Atidaryti darbo meniu',
    no_nearby = 'Nieko nerasta',
    no_nearby_desc = 'Atrodo šalimais nieko nėra',
    invalid_entry = 'Netinkamas įrašas',
    invalid_entry_desc = 'Įveskite tinkamą skaičių',
    fines = 'Baudos',
    fines_desc = 'Išrašyti baudą artimiausiam asmeniui',
    search_player = 'Apieškoti įtariamąjį',
    search_player_desc = 'Apieškoti artimiausią asmenį',
    jail_player = 'Įkalinti įtariamajį',
    jail_player_desc = 'Įkalinti artimiausią asmenį',
    minutes_dialog = 'Bausmės skyrimas',
    minutes_dialog_field = 'Mėnesiai',
    escort_player = 'Lydėti įtariamąjį',
    escort_player_desc = 'Lydėti artimiausią asmenį',
    handcuff_hard_player = 'Surakinti įtariamąjį (sunkiai)',
    handcuff_hard_player_desc = 'Surakinti artimiausią asmenį (sunkiai)',
    handcuff_soft_player = 'Surakinti įtariamąjį (lengvai)',
    handcuff_soft_player_desc = 'Surakinti artimiausią asmenį (lengvai)',
    put_in_vehicle = 'Įsodinti asmenį',
    put_in_vehicle_desc = 'Įsodinti asmenį į artimiausią tr. priemonę',
    check_id = 'Patikrinti tapatybę',
    check_id_desc = 'Patikrinti artimiausio asmens ID',
    id_result_menu = 'Asmens tapatybė',
    name = 'Vardas',
    job = 'Darbas',
    job_position = 'Pareigybė',
    dob = 'Gimimo data',
    sex = 'Lytis',
    bac = 'BAC',
    licenses = 'Licencijos',
    total_licenses = 'Iš viso licencijų:',
    no_licenses = 'Nėra licencijų',
    revoke_license = 'Atimti licenciją',
    license_revoked = 'Licencija atimta',
    license_revoked_desc = 'Sėkmingai atėmei licenciją',
    armoury_menu = 'Ginklų saugyklos meniu',
    take_out_vehicle = 'Išlaipinti asmenį',
    take_out_vehicle_desc = 'Išlaipinti asmenį iš tr. priemonės',
    not_restrained = 'Įtariamasis nėra surakintas',
    not_restrained_desc = 'Turite surakinti asmenį norėdami jį lydėt',
    vehicle_not_found = 'Transporto priemonė nerasta',
    vehicle_not_found_desc = 'Šalia nerasta jokių tr. priemonių',
    unconcious = 'Asmuo be sąmonės',
    unconcious_desc = 'Atrodo, kad asmuo yra be sąmonės',
    police_garage = 'Garažas',
    police = 'Policija',
    plate = 'Valstybiniai numeriai',
    owner = 'Savininkas',
    possibly_stolen = 'Atsargiai!',
    possibly_stolen_desc = 'Transporto priemonė yra galimai vogta',
    vehicle_interactions = 'Veiksmai su tr. priemonę',
    vehicle_interactions_desc = 'Tikrinkite arčiausią transporto priemonę',
    vehicle_information = 'Tr. priemonės informaciją',
    vehicle_information_desc = 'Artimiausios tr. priemonės informacija',
    lockpick_vehicle = 'Išlauštį spyną',
    locakpick_vehicle_desc = 'Įsilaužti artimiausios tr. priemonės spyną',
    lockpick_progress = 'Išlaužiama spyna . . .',
    too_far = 'Per toli',
    too_far_desc = 'Pasirinkta tr. priemonė yra per toli',
    lockpicked = 'Sėkmingai atrakinta',
    lockpicked_desc = 'Sėkmingai atrakinai transporto priemonę',
    cancelled = 'Atšaukta',
    cancelled_desc = 'Atšaukei paskutinį savo veiksmą',
    impound_vehicle = 'Sulaityki tr. priemonę',
    impound_vehicle_desc = 'Sulaikyti transporto priemonę',
    impounding_progress = 'Tr. priemonė sulaikoma . . .',
    driver_in_car = 'Vairuotojas mašinoje',
    driver_in_car_desc = 'Pašalinkite vairuotoją iš tr. priemonės prieš ją sulaikant!',
    car_impounded_desc = 'Tr. priemonė buvo sulaikyta',
    place_object = 'Padėti objektą',
    place_object_desc = 'Padėti objektą ant žemės.',
    prop_help_text = 'Spauskite ~INPUT_CONTEXT~ norint perkelti objektą.\nSpauskite ~INPUT_DETONATE~ norėdami ištrinti objektą.',
    prop_help_text2 = 'Spauskite ~INPUT_CONTEXT~ norėdami padėti objektą.',

    fine_sent = 'Bauda išsiusta',
    fine_sent_desc = 'Jūs sėkmingai išsiustėte $%s baudą!',
    fine_received = 'Gauta bauda',
    fine_received_desc = 'Gavote $%s baudą',
    male = 'Vyras',
    female = 'Moteris',
    mr = 'Ponas',
    mrs = 'Ponia',
    debt_collection = 'Skolos surinkimas',
    db_email =
    '%s %s, <br /><br />Centrinė Teisminė Įstaiga priverstinai sumokėjo baudas kurias gavote iš policijos.<br />Buvo nuskaičiuoti <strong>$%s</strong> iš jūsų sąskaitos.<br /><br />Su pagarba,<br />Mr. Bad Fox',

    spawn_blocked = 'Gažaras užblokuotas',
    spawn_blocked_desc = 'Negalite ištraukti tr. priemonės nes ji yra užblokuota!',


    --GSR New
    positive = 'Teigiamas',
    positive_gsr_desc = 'Ant įtariamojo buvo SĖKMINGAI aptikti šūvių parako likučiai!',
    negative = 'Neigiamas',
    negative_gsr_desc = 'Ant įtariamojo nebuvo aptikti šūvių parako likučiai!',
    gsr_test = 'Šūvio likučių testas',
    gsr_test_desc = 'Patikrinti artimiausią asmenį šūvio likučių testu',
    hands_clean = 'Nuplautos',
    hands_clean_desc = 'Sėkmingai nuplovėte šūvio liekanas nuo savo rankų!',
    gsr_wash_ui = '[E] - Plauti rankas',

    -- Go on/off duty new
    on_duty = 'Pradėti darbą',
    on_duty_desc = 'Jūs pradėjote darbą!',
    off_duty = 'Baigti darbą',
    off_duty_desc = 'Jūs baigėte darbą!',

    robbing_player = 'Apiplėšinėjate asmenį. . .',

    cancelled_action = 'Veiksmas atšauktas',
    cancelled_action_desc = 'Jūsū paskutinis veiksmas buvo atšauktas',

    no_cuffs = 'Nėra antrankių',
    no_cuffs_desc = 'Jūs savo kišenėse neturite antrankių!',
    failed = 'Nepavyko',
    lockpick_handcuff_success = 'Sėkmingai išsilaisvinote iš antrankių!',
    lockpick_handcuff_fail = 'Jums nepavyko atsirakinti antrankių!',
    lockpick_broke = 'Jūsų įrankis sulužo',
    lockpick_broke_desc = 'Jūsų įrankis kuri naudojote sulužo!',
    grant_license = 'Išduoti ginklo licenciją',
    grant_license_desc = 'Išduoti ginklo licenciją artimiausiam asmeniui',
    player_id = 'Žaidėjo ID:',
    select_player = 'Pasirinkite asmenį',
    license_granted = 'Licencija suteikta',
    license_granted_desc = 'Jūs suteikėte licenciją šiam asmeniui %s (%s)',
    license_alr_granted = 'Šis asmuo jau turi licenciją!',
    weapon_license = 'Ginklų licencija',
    weapon_license_desc = 'Jūs gavote ginklo licenciją.',

    in_vehicle = 'Transporto priemonėje',
    in_vehicle_desc = 'Negalite sulaikyti asmens, nes jis yra tr. priemonės viduj!',

    grade_to_low = 'Per žema pareigybė',
    grade_to_low_desc = 'Jūsų pareigybė per žema šiam veiksmui',
    invoice_amount = 'Sąskaitos suma',
    amount_invoice = 'Suma',
    reason_invoice = 'Priežastis',
    gov_billing = 'Valstybės skolų surinkimas'
}
